### ISSUE TITLE
How do you access a video thumbnail

### ISSUE THREAD

**Issue by nebhob** [mfilippov/vimeo-dot-net#102]
I'm able to gain access to a list of videos like this:
Paginated(Of Video) vList = vimeoClient.GetAlbumVideosAsync(_vimeoSettings.AlbumID, 1, 50)
   
How do you get the thumbnail of each video?
vList.data contains a list of videos and can get most properties like the video id from each with no problem but am having a hard time figuring out how to access the thumbnail.

**Comment by mfilippov** [comment]
@nebhob I fix some API issues and add the test for retrieve video pictures.
