### ISSUE TITLE
add a way to verify an access token

### ISSUE THREAD

**Issue by AndrewKoransky** [mfilippov/vimeo-dot-net#109]
From what I can see, Vimeo has little documentation stating when an access token will expire. But there is a quick way to check if an access token is still good, and it would be a nice feature to add I think:

[https://developer.vimeo.com/api/endpoints/authenticationextras#GET/oauth/verify](https://developer.vimeo.com/api/endpoints/authenticationextras#GET/oauth/verify)

**I will be issuing a pull request** with this additional functionality added momentarily.

**Comment by mfilippov** [comment]
@AndrewKoransky Thanks for the contribution. I ship new package when I finished .NET Core refactoring.

**Comment by mfilippov** [comment]
@AndrewKoransky  I shipped new version with .NET Standard support. You fix should be available in NuGet.
