### ISSUE TITLE
GetVideosAsync return Service unavailable

### ISSUE THREAD

**Issue by t1er** [mfilippov/vimeo-dot-net#111]
Hi 

Message: {"error":"An error has occurred while searching for videos. Please try again.","link":null,"developer_message":"Search is currently unavailable. Please retry your request.","error_code":7300}

Regarding doc https://developer.vimeo.com/api/endpoints/videos seems problem on their side, but it works for GetVideoAsync(video_id).

Maybe I should enable API search for my account somewhere?

Thanks

**Comment by mfilippov** [comment]
@t1er Thank you for the feedback. Try to reproduce on the latest version. May be you API key don't have enough permissions?

**Comment by mfilippov** [comment]
@t1er Issue is actual?

**Comment by mfilippov** [comment]
I close this issue as obsolete if you still have a problem, please reopen.
