### ISSUE TITLE
Doesn't support albums with videos?

### ISSUE THREAD

**Issue by vurso** [mfilippov/vimeo-dot-net#117]
Hi great project, I can't see how to get videos contained inside an album as per this API page:

https://developer.vimeo.com/api/endpoints/albums#GET/users/{user_id}/albums/{album_id}/videos

Happy to branch the source and implement this feature unless you're already planning to implement it?

**Comment by mfilippov** [comment]
Hi, this API already implemented. See on tests:
https://github.com/mfilippov/vimeo-dot-net/blob/7250695a9d0b7b3dbe517ada40bf338e4221c5e0/src/VimeoDotNet.Tests/VideoTests.cs#L95
https://github.com/mfilippov/vimeo-dot-net/blob/7250695a9d0b7b3dbe517ada40bf338e4221c5e0/src/VimeoDotNet.Tests/VideoTests.cs#L104

**Comment by vurso** [comment]
Hi thank you for the response, odd the nuget package I downloaded in VS 2017 didn't seem to have support so I assumed the feature wasn't there (I may have downloaded an old version?).

Will give the above a go tonight thank you for your help.
