### ISSUE TITLE
Need for ConfigureAwait(false)?

### ISSUE THREAD

**Issue by mohibsheth** [mfilippov/vimeo-dot-net#118]
I've been using VimeoDotNet for a while in my WebAPI project

Recently I started having a problem with GetVideoAsync method. It never returned. I found HttpClient to be the cause, the code never returns from Client.SendAsync in APIRequest.ExecuteRequestAsync
https://github.com/mfilippov/vimeo-dot-net/blob/master/src/VimeoDotNet/Net/ApiRequest.cs#L159

Upon a bit of research, I found other people having similar problems (with HttpClient and not VimeoDotNet) and they recommended `ConfigureAwait(false)`.

I tried that and it resolves the issue. To make it work properly through and through, I had to add `ConfigureAwait(false)` in ExecuteRequestAsync and GetVideoAsync

What do you think? Is ConfigureAwait required? Or am I doing something wrong?

**Comment by aazbeltran** [comment]
I have the same problem

**Comment by mohibsheth** [comment]
@mfilippov Could you please assist with this?

**Comment by mfilippov** [comment]
@mohibsheth Yes, it try to find some time little bit latter.

**Comment by mfilippov** [comment]
@mohibsheth I found reason of the problem. If you call Wait() or Result with save SynchronizeContext an example call from UI thread. I use ConfigureAwait(false) for all await calls.

**Comment by mfilippov** [comment]
You could read https://msdn.microsoft.com/en-us/magazine/jj991977.aspx to get details.

**Comment by mfilippov** [comment]
Fixed in 1.0.0.9

**Comment by mohibsheth** [comment]
Thanks for the confirmation and the fix @mfilippov!
