### ISSUE TITLE
Will vimeodotnet support .NET Core 2.1?

### ISSUE THREAD

**Issue by oattie** [mfilippov/vimeo-dot-net#119]
Hi guys,

Thanks for a wonderful C# wrapper but I wonder if you guys are planning to support .NET Core 2.1 ?
I have an application that has been developing under .NET Core 2.1 version and I could not use ViemoDotNet to upload videos.

Best regards,
AP

**Comment by mfilippov** [comment]
@oattie Yes we supported .NET Core 2.1, Vimeo.NET required .NET 4.5/.NET Standard 1.3.
