### ISSUE TITLE
How do I start using this API

### ISSUE THREAD

**Issue by itorian** [mfilippov/vimeo-dot-net#121]
Hello, looks awesome api for vimeo. Can you please guide me to use this api.

**1. Using id and secret:**

    VimeoClient client = new VimeoClient("xxxx", "xxxx");
    var videos = client.GetVideosAsync(xxxx, 0, 0);

![image](https://user-images.githubusercontent.com/3646552/44018772-74fe270a-9efa-11e8-8a83-67512583fa5d.png)

**2. If I use it another way using token, that's the result:**

![image](https://user-images.githubusercontent.com/3646552/44020700-5c347d2c-9f00-11e8-8d0b-efb64421f7de.png)

What is the meaning of "WaitingForActivation"? Is this because API app is not approved ?

Also, which technique I should use in our web app (SaaS) if I would like to upload multiple videos in multiple browsers instance same time?

**Comment by mfilippov** [comment]
@itorian you should use await to call async function.
```
VimeoClient client = new VimeoClient("xxxx", "xxxx");
var videos = await client.GetVideosAsync(xxxx, 0, 0);
```

**Comment by itorian** [comment]
Please authenticate via OAuth to obtain an access token.
Do we have any documentation ?

**Comment by mfilippov** [comment]
Authentication process described in Vimeo API docs: https://developer.vimeo.com/api/authentication

**Comment by mavericken** [comment]
It seems like people actually use this library...  It is surprising that nobody gave a proper answer to this.  If I figure it out, I'll post it here.

**Comment by mavericken** [comment]
OK, I figured it out.  Here is an example showing how you can use this library to authenticate.
```
            var clientId = "your_client_id_here";
            var clientSecret = "your_client_secret_here";
            var redirectionUrl = "https://your_website_here.com/wherever-you-send-users-after-grant"; // this URL needs to be added to your callback url list on your app settings page in developer.vimeo.com
            var stateInformation = "1337"; //you can put state information here that gets sent to your callback url in the ?state= parameter
            var client = new VimeoDotNet.VimeoClient(clientId, clientSecret);
            var url = client.GetOauthUrl(redirectionUrl, new List<string>() { "public", "private", "purchased", "create", "edit", "delete", "interact", "upload", "promo_codes", "video_files" }, stateInformation);
            Console.WriteLine(url);
            Console.WriteLine("Give me your access code...");
            var accessCode = Console.ReadLine();
            var code = await client.GetAccessTokenAsync(accessCode, redirectionUrl);
            var token = await client.GetAccessTokenAsync(accessCode, redirectionUrl);
            var userAuthenticatedClient = new VimeoDotNet.VimeoClient(token.AccessToken); //we need a new client now, if it is a one off job you can just
            //you are now ready to upload or whatever using the userAuthenticatedClient
```

**Comment by mfilippov** [comment]
@mavericken It would be good if you would send PR with documentation. Or maybe README update.

**Comment by mavericken** [comment]
@mfilippov I have created the pull request for including the example and some instructions in the README.
