### ISSUE TITLE
VimeoUploadVideo returns "Error generating upload ticket"

### ISSUE THREAD

**Issue by PaoloLeva** [mfilippov/vimeo-dot-net#124]
Since few days I cannot anymore upload videos to Vimeo. The error I get is "Error generating upload ticket" when calling "VimeoUploadVideo".
Nothing has changed in my code or setup since long time. I tried updating the library but still the same error.
Anyone able to help me out or point me in the right direction? My service is now staying still and nothing works.

**Comment by PaoloLeva** [comment]
Thanks @mfilippov I did and I found the source of the issue, which was that I lacked support for TLS 1.2 (so not directly related to the library). Thanks for your help and your great work!

**Comment by rokag3-gb** [comment]
Good day, Sir. Could you please share how you solved the "Error generating upload ticket" response from Vimeo by changing the TLS settings? It would be really helpful if you could let me know.
