### ISSUE TITLE
AddToAlbumAsync doesn't have tests and doesn't work for UserId.Me

### ISSUE THREAD

**Issue by rleeson24** [mfilippov/vimeo-dot-net#129]
I am attempting to add videos to an album for my own account, but it will not do it because it attempts to use the url /users/me/albums.... when it should be using /me/albums....

**Comment by junminahn** [comment]
the fix is very straight-forward; in VimeoClient_Albums.cs
the line 104 should be:
    Endpoints.GetCurrentUserEndpoint(Endpoints.UserAlbumVideo),

just like other endpoints.

**Comment by mfilippov** [comment]
Fixed in 2.0.0.18
