### ISSUE TITLE
Can't understand how to start uploading videos through the API

### ISSUE THREAD

**Issue by Ahmed-Sajjad** [mfilippov/vimeo-dot-net#131]
Hi, I just started using the API but haven't figured out how to use it at all.

How do I upload videos? A related issue was about providing examples. BUt even a quick beginners guide in the docs will also do.

Many thanks in advance

**Comment by mfilippov** [comment]
@Ahmed-Sajjad You could look into our tests to understand who it works.

**Comment by mfilippov** [comment]
An example: https://github.com/mfilippov/vimeo-dot-net/blob/eb7309a70a7d53d4773d5ffdaaf8b06485d2bd0d/src/VimeoDotNet.Tests/VideoTests.cs#L14

**Comment by Ahmed-Sajjad** [comment]
Great, thank you so much for your help.
