### ISSUE TITLE
replace video using pull

### ISSUE THREAD

**Issue by mohammed-gaber-ramadan** [mfilippov/vimeo-dot-net#147]
need to pass old video ID while using UploadPullLinkAsync() method to be able to replace video the same as in Resumable

**Comment by WhiskeyGolf** [comment]
Is there an easy work around to updating a video with pull? Currently can't seem to find a way to do it.

**Comment by mfilippov** [comment]
@WhiskeyGolf no easy way to do it. PR are welcome.

**Comment by mfilippov** [comment]
Fixed via #180
