### ISSUE TITLE
Thumbnails are not available (GetPicturesAsync) right after uploading the video

### ISSUE THREAD

**Issue by AlvexGR** [mfilippov/vimeo-dot-net#156]
Hi, I would like to get default thumbnails of my video after I successfully upload it. I'm using GetPicturesAsync but the thumbnails are not available yet until a few seconds later.
Do we have a way to wait for it or webhook on this?

**Comment by mfilippov** [comment]
No, I think it is not part of Vimeo API. I think waiting for any processing is the API client's responsibility.

**Comment by nhannn-imt** [comment]
Thank you very much, I have a workaround solution with background task.

**Comment by AlvexGR** [comment]
Thank you very much, I have a workaround solution with background task.
