### ISSUE TITLE
I get all video information but do not get the images

### ISSUE THREAD

**Issue by drumset** [mfilippov/vimeo-dot-net#18]
I get all video information but do not get the images.

VimeoDotNet.IVimeoClient cliente = new VimeoDotNet.VimeoClient(accessToken);
 VimeoDotNet.Models.Video video = cliente.GetVideo(idvideo);

Results:
pictures.Count = 6
pictures.active = false
pictures.sizes = null
pictures.uri = null

**Comment by stukalin** [comment]
I think I fixed the issue by commit a4a2e0c2b4f04e652b6a80d1ef403198e3ffcae2

**Comment by scommisso** [comment]
This looks to be fixed to me, as well. I see the pictures in the integration tests.
