### ISSUE TITLE
Cant seem to upload video via a free account

### ISSUE THREAD

**Issue by SaqibAsthaIT** [mfilippov/vimeo-dot-net#186]
I am currently using a free account to upload videos to my vimeo account. 
![image](https://user-images.githubusercontent.com/117251768/232264541-24fb7ee8-6ef9-4815-9b74-2d3c9ab166c3.png)
I have space to upload a video, please see the attached image. But I seem to get an error in this check ```if (fileContent.Data.Length > ticket.User.UploadQuota.Space.Free)```

I am using _vimeoClient.UploadEntireFileAsync method. Can someone tell me where Im going wrong?

Thanks

**Comment by leonardoacoelho** [comment]
Hi, I've opened a pull request #192  to fix this error, if you could check if te changes I made make any sense for you @mfilippov

**Comment by mfilippov** [comment]
@SaqibAsthaIT Could you provide sample of JSON answer from the server?

**Comment by mfilippov** [comment]
Fix available in v3.2.4
