### ISSUE TITLE
Error generating upload ticket. Code: BadRequest

### ISSUE THREAD

**Issue by SandipJawaleRN** [mfilippov/vimeo-dot-net#194]
Error while uploading

`Message: {"invalid_parameters":[{"field":"type","error_code":2552,"error":"The streaming approach is no longer functional. For alternatives, 
please visit https://developer.vimeo.com/api/upload/videos#understanding-upload-approaches.",
"developer_message":"The streaming approach is no longer functional. For alternatives, please visit https://developer.vimeo.com/api/upload/videos#understanding-upload-approaches."}],
"error":"You have provided an invalid parameter. Please contact developer of this application.",
"link":null,"developer_message":"The parameters passed to this API endpoint didn't pass Vimeo's validation. Please check the invalid_parameters list for more information.","error_code":2204}`

@mfilippov
Please help
Thanks

**Comment by mfilippov** [comment]
@SandipJawaleRN Which version of library do you use? I change upload approach in the latest version.

**Comment by SandipJawaleRN** [comment]
Ok i am updating to latest version.
It was working till 30th June.

Thanks @mfilippov  for reply

**Comment by SandipJawaleRN** [comment]
Thanks Uploading working now!!
