### ISSUE TITLE
GetAccountVideoAsync not getting videos?

### ISSUE THREAD

**Issue by jhang** [mfilippov/vimeo-dot-net#2]
It might be an issue on vimeo's end. When calling GetAccountVideoAsync with a valid clip id, it's not returning anything. Is this working for you? I uploaded a video through the api but set the privacy to only be accessible through me. When the video's privacy is set to "Hide this video from Vimeo.com", the request returns null. When it's set to "Anyone", the data is returned. 

I'm calling this with an AccessToken. Are you calling it with something else?

**Comment by mfilippov** [comment]
@jhang I close this issue as obsolete. We have some tests for that case.
