### ISSUE TITLE
Error executing GetVideoAsync method

### ISSUE THREAD

**Issue by humbertolopezleon** [mfilippov/vimeo-dot-net#204]
A couple of hours ago we detected an unhandled exception when executing the GetVideoAsync method. Here are the details:

Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'VimeoDotNet.Models.UserInteractions' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly.
To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.
Path 'user.metadata.interactions', line 1, position 13213.
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

Exception Details: Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'VimeoDotNet.Models.UserInteractions' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly.
To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.
Path 'user.metadata.interactions', line 1, position 13213.

Source Error:

Line 299:			// Grab video info from VIMEO
Line 300:			var vimeoClient = new VimeoClient(VIMEO_API_KEY); 
Line 301:			var video = await vimeoClient.GetVideoAsync(videoID).ConfigureAwait(false);

Stack Trace:

[JsonSerializationException: Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'VimeoDotNet.Models.UserInteractions' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly.
To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.
Path 'user.metadata.interactions', line 1, position 13213.]
   Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureArrayContract(JsonReader reader, Type objectType, JsonContract contract) +280
   Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id) +123
   Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue) +215
   Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target) +368
   Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id) +2635
   Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue) +775
   Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue) +168
   Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target) +368
   Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id) +2635
   Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue) +775
   Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue) +168
   Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target) +368
   Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id) +2635
   Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue) +775
   Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue) +168
   Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent) +749
   Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType) +264
   Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings) +170
   Newtonsoft.Json.JsonConvert.DeserializeObject(String value, JsonSerializerSettings settings) +53
   VimeoDotNet.Net.<ExecuteRequestAsync>d__64`1.MoveNext() +861
   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +32
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +62
   VimeoDotNet.<GetVideoAsync>d__86.MoveNext() in C:\projects\vimeo-dot-net\src\VimeoDotNet\VimeoClient_Videos.cs:22

[VimeoApiException: Error retrieving account video.]
   VimeoDotNet.<GetVideoAsync>d__86.MoveNext() in C:\projects\vimeo-dot-net\src\VimeoDotNet\VimeoClient_Videos.cs:35
   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +32
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +62
   System.Runtime.CompilerServices.ConfiguredTaskAwaiter.GetResult() +32
   <GetVimeoVideoAsync>d__39.MoveNext() in C:\home\site\wwwroot\hs\ViewContent.aspx.cs:301
   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +32
   System.Web.UI.<ExecuteTasksAsync>d__3.MoveNext() +450
   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +32
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +62
   System.Web.UI.<ProcessRequestAsync>d__554.MoveNext() +985

I suspect it is an internal error due to some change in the Vimeo API. Please let us know if you have any idea on how to fix this. Thanks

**Comment by MineKayaa** [comment]
We have the same issue, it would be so great to hear some news

**Comment by ronann** [comment]
It's the interactions field in the UserMetadata.cs file under Models. It looks like the vimeo API is returning a list instead of an object for that field and the deserialization is blowing up.

**Comment by gtsoftwareltd** [comment]
> Facing the same issue. How can i fix it in my code manually?

I can confirm @ronann suggestion works.

Cloning vimeo-dot-net and changing UserMetadata.cs

```
        /// <summary>
        /// Interactions
        /// </summary>
        [PublicAPI]
        [JsonProperty(PropertyName = "interactions")]
        public List<UserInteractions> Interactions { get; set; }
```

In my VS2022 solution, I removed the NuGet VimeoDotNet package and added the cloned VimeoDotNet project to my solution with a project reference. No other changes, build, run and my existing test application is working again (minimal testing).

The real fix will need a few of the test cases updating.

There is always the possibility that Vimeo will revert their recent change.

**Comment by DanPatten** [comment]
Could also just delete Interactions prop in case it gets reverted, just depends if that is used.

**Comment by JagadeesanCoastal9714** [comment]
unhandled exception when executing the GetVideoAsync method Same issue any help Please!. very urgent

**Comment by Ashalls** [comment]
Also facing this, please fix, its totally broken our functiaonlity.

**Comment by DanPatten** [comment]
@mfilippov

**Comment by larskn** [comment]
It seems this was an unintentional change in the Vimeo API, this is why there was nothing written about in in the changelog or in the docs.

Vimeo support told me they deployed a fix for the issue. Our application is now running again without any errors. So I guess this issue can be closed.

**Comment by mfilippov** [comment]
@larskn  Thank you for the investigation!
