### ISSUE TITLE
Cannot get Thumbnails when using from nuget

### ISSUE THREAD

**Issue by PaoloLeva** [mfilippov/vimeo-dot-net#21]
When using GetVideoAsync from NuGet package i don't get the Thumbnails.
After investigating I noticed that "VimeoDotNet.Models.Picture" is defined differently in NuGet compared to the code that I can download from github.

From NuGet (erroneous definition):

    namespace VimeoDotNet.Models
    {
        [Serializable]
        public class Picture
        {
            public Picture();

            public int height { get; set; }
            public string link { get; set; }
            public PictureTypeEnum PictureType { get; set; }
            public string type { get; set; }
            public int width { get; set; }
        }
    }

From the code downloaded here (correct definition):

    namespace VimeoDotNet.Models {
        [Serializable]
        public class Picture {
            public bool active { get; set; }
            public string uri { get; set; }
            public List<Size> sizes { get; set; }
        }
    }

**Comment by stukalin** [comment]
I think I fixed the issue by commit a4a2e0c2b4f04e652b6a80d1ef403198e3ffcae2

**Comment by mfilippov** [comment]
Should be fixed in 0.7.4. NuGet package updated.

**Comment by PaoloLeva** [comment]
Thanks mfilippov, but via nuget interface in VS2013 I do not see the update yet.

**Comment by mfilippov** [comment]
@PaoloLeva Try now I add multiple frameworks target in package.

**Comment by PaoloLeva** [comment]
@mfilippov everything works great! Thanks a lot, great job!
