### ISSUE TITLE
Vimeo API working fine with Test case but not with windows application

### ISSUE THREAD

**Issue by sehaj018** [mfilippov/vimeo-dot-net#26]
Hi,

I am working on vimeo api and download example code. Its working fine for Test case(VimeoDotNet.Tests).  but when i try with windows application(C#) and pass reference of Vimeodotnet dll. its not working for sync call methods. My screen hang after call sync method.Please help me to find out issues.

Thanks in advance

**Comment by mfilippov** [comment]
Can you give me code sample with problem?

**Comment by scommisso** [comment]
I'll take a look at the async/sync.

**Comment by sehaj018** [comment]
Thanks for quick reply, 

Scommisso , Your code working fine for me.
