### ISSUE TITLE
How to get "access_token"?

### ISSUE THREAD

**Issue by Englbach** [mfilippov/vimeo-dot-net#30]
I got client_id, client_secret...and resfesh token when expire code.

**Comment by scommisso** [comment]
Use the `VimeoClient` constructor that takes `clientId` and `clientSecret`. The `accessToken` constructor is for use with calls with a private access token that you can request on the Vimeo API Developer Account page (should be an option called Generate Access Token)

When using `clientId` and `clientSecret`, you're going to want to use the `GetOauthUrl()` method, followed by `GetAccessTokenAsync()` when you receive the `authorizationCode` callback from Vimeo.

**Comment by saniaaa** [comment]
Hello! 
Can you guide me that how to use API for visual studio 2010. I want to search videos and get list of video URL.
Thanks

**Comment by t1er** [comment]
Hi @scommisso 

Trying to use this library:

var c = new VimeoClient("mytoken");
allVideos = c.GetVideos();  ---->>>exception

{"Could not load type 'RestSharp.Authenticators.IAuthenticator' from assembly 'RestSharp, Version=105.1.0.0, Culture=neutral, PublicKeyToken=null'.":"RestSharp.Authenticators.IAuthenticator"}

all dlls exist in bin folder

**Comment by mfilippov** [comment]
@t1er can you attach sample project with this problem?

**Comment by t1er** [comment]
@mfilippov https://github.com/t1er/testvimeodotnetconsole

**Comment by bluemoon1894** [comment]
Hi @scommisso, @mfilippov did you manage to find a solution for this? I have the same RestSharp error when running this code (or anything else I try):

var c = new VimeoClient("my token generated in vimeo");
Paginated<Video> videos = c.GetUserVideos(12345678, 1, 10);

It's asp.net 4.5 website, in visual studio 2015. I'm using RestSharp v105.2.3 

Thanks.

**Comment by mfilippov** [comment]
@bluemoon1894 I think I found reason of problem. I try to build new version at the weekend.

**Comment by bluemoon1894** [comment]
Thanks @mfilippov any luck?

I have tried installing Restsharp v105.1.0 but still get the same error.

I also downloaded the source and changed the vimeodotnet.nuspec lines as shown here, then added this project as a reference, using RestSharp 105.2.3. But I still get the same error.

[Fix RestSharp Version](https://github.com/mfilippov/vimeo-dot-net/pull/89/commits/1cedcce4b0fc0be71c3a8b3b1e0f525756714d7e#diff-2c1266c2f5a309a58fb61a11b3212f5c)

Thanks

**Comment by mfilippov** [comment]
Thanks for the contribution. I approved PR and deploy a new version to nuget.org. Now I try to make new library version without RestSharp dependency.

**Comment by bluemoon1894** [comment]
Hi @mfilippov 

Thanks for the new version. I'm still not getting any success though. To remind you what I have done I've listed the steps below. Maybe some usage documentation for video-dot-net would be a good idea?

So in my vimeo account I have generated an access token with public and private scopes.
In my code (asp.net 4.5 MVC website) I have:

```
using VimeoDotNet;
using VimeoDotNet.Net;
using VimeoDotNet.Models;

protected void btnImport_Click(object sender, EventArgs e)
        {
            if (Page.IsValid)
            {
try
                {
                    VimeoClient vc = new VimeoClient("<insert my access token id here>");
                    Paginated<Video> videos = vc.GetUserVideos(<insert my user id number here>, 1, 10);                  
                }
                catch(Exception ex)
                {
                    string x = ex.Message;
                }
}
}
```
Is that all that is required to fetch the paged video list for my user ID or have I missed something?

When I run that in the debugger with a breakpoint set, it just hangs after the 'GetUserVideos' line and doesn't give me anything back, even the 'catch exception' is not fired.

I have vimeoDotNet 0.8.3.50 and RestSharp 105.2.3 installed in the solution.

Thanks
