### ISSUE TITLE
vimeo-dot-net show error when installing from nuget on VS 2015 RC

### ISSUE THREAD

**Issue by Englbach** [mfilippov/vimeo-dot-net#31]
VimeoDotNet3 
Severity    Code    Description Project File    Line
Error       Could not install package 'RestSharp 105.1.0'. You are trying to install this package into a project that targets 'Windows,Version=v8.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.          0

**Comment by mfilippov** [comment]
@Englbach Can you reproduce it in 2015 Release?

**Comment by mfilippov** [comment]
@Englbach I remove the dependency on RestSharp issue should be fixed.
