### ISSUE TITLE
How to show upload progress when the upload a video?

### ISSUE THREAD

**Issue by tndevjp** [mfilippov/vimeo-dot-net#32]
This API's very good, I can upload video to Vimeo server, but how do i can show the progress of the upload progress.
Thanks in advance.

**Comment by scommisso** [comment]
You can take a look at the code here:
https://github.com/mfilippov/vimeo-dot-net/blob/68004d130eaf8d1ca869d63240d33d20a0e5e837/src/VimeoDotNet/VimeoClient_Upload.cs#L134-L169

The methods it calls are public, so you can use the same approach to provide progress notification.

We can also look at adding an event to the client, or allowing an optional callback function to be passed in.

**Comment by tndevjp** [comment]
Thanks you for the help. 
Another problem I need help from you, I can update the information for a video that I uploaded via the function "GenerateVideoPatchRequest" in file "VimeoClient_Videos.cs" . But I could not find information about the "tag", I have added the following:
            if (metaData.Tags != null)
            {
                request.Query.Add("tags", metaData.Tags.ToString().ToLower());
            }
            //metaData.Tags is a string object
But it does not work, I hope to receive help from you.

**Comment by mfilippov** [comment]
@tndevjp I add support API for tag modification in #114.
