### ISSUE TITLE
Getting data from the next page

### ISSUE THREAD

**Issue by agricfowl** [mfilippov/vimeo-dot-net#33]
I am using GetAlbumVideos(albumID) and by default, it seems to only return the first page restricted to 25 items. 
How do l use this method to return the rest of the data that don't belong to the first page?
If need be, how do l increase the page size (per_page)?

**Comment by mfilippov** [comment]
I try add it in API.

**Comment by agricfowl** [comment]
Hi Filippov

I have added it myself to my local copy. Really I should send it to you via the proper channels but I am currently on holidays. Should be back at work on Monday. Will make a pull request then and submit my changes for review

**Comment by mfilippov** [comment]
Ok i'll wait.

**Comment by scommisso** [comment]
I see the `page` and `perPage` parameters on `GetAlbumVideos` now, so I'm assuming we can close this?

**Comment by agricfowl** [comment]
Yes please

Regards
Derrick
