### ISSUE TITLE
How to set redirect_url?

### ISSUE THREAD

**Issue by ilFusta** [mfilippov/vimeo-dot-net#34]
Hi, 
Is there the possibility to set a custom redirect_url in the GetUploadTicket call?

**Comment by mfilippov** [comment]
@ilFusta Thank you for the feedback. Sorry for the long delay. Could you describe your use case?

**Comment by mfilippov** [comment]
@ilFusta I close this issue as obsolete feel free reopen I the problem still actual for you.
