### ISSUE TITLE
Set domain whitelist

### ISSUE THREAD

**Issue by callumelgrant** [mfilippov/vimeo-dot-net#42]
Hi there,

There's currently no support in the library for setting the domain whitelist for videos - if I add the functionality and make a PR would you accept it? 

Cheers,

Callum

**Comment by scommisso** [comment]
Yes, that would be welcome. Thank you.

**Comment by mfilippov** [comment]
@callumelgrant Domain whitelisting feature available. I can't write the test for this feature right now because it API worked only on Pro accounts.
