### ISSUE TITLE
0.8.0 not compatible with .NET 4.5?

### ISSUE THREAD

**Issue by PaoloLeva** [mfilippov/vimeo-dot-net#44]
I tried to upgrade to 0.8.0 but I get this message:

Could not install package 'VimeoDotNet 0.8.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Is this the expected behaviour?

**Comment by scommisso** [comment]
@mfilippov - I was publishing to NuGet from the `/src/VimeoDotNet/` folder, which version target had you been publishing to NuGet?

**Comment by izaxon** [comment]
We get the these messages when trying to add the nuget package.

Attempting to resolve dependencies for package 'VimeoDotNet.0.8.0' with DependencyBehavior 'Lowest'
Resolving actions to install package 'VimeoDotNet.0.8.0'
Resolved actions to install package 'VimeoDotNet.0.8.0'
Install failed. Rolling back...
Package 'VimeoDotNet 0.8.0' does not exist in project 'SlideTalkLibrary'
Package 'VimeoDotNet 0.8.0' does not exist in folder 'C:\Users\Johan\Source\Workspaces\SlideTalk\SlideTalk\packages'
Could not install package 'VimeoDotNet 0.8.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by izaxon** [comment]
We use VS2015. Downloading the source, included the VimeoDotNet.Net45 project in our solution and referenced it from our project that could not add the NuGet package. It did not build, but removing the RestSharp nuget ref and adding in again (to VimeoDotNet.Net45) solved it. Now it builds.

**Comment by mfilippov** [comment]
@scommisso You should use build.bat for build multi-target package. I can do it later.

**Comment by mfilippov** [comment]
I want to setup Travis CI for auto package.

**Comment by cornem** [comment]
Running into the same issue here. Cannot update to 0.8.0 on v4.5.

**Comment by GFoley83** [comment]
:+1: Same here. Can't install into my 4.5 solution.

**Comment by scommisso** [comment]
This should be fixed, `0.8.1` is published with multiple targets.
