### ISSUE TITLE
RestSharp error

### ISSUE THREAD

**Issue by mackeym** [mfilippov/vimeo-dot-net#47]
Hi, I feel like I'm missing something obvious here.  I've been trying to authenticate using every way I can find and so far I just keep running into the same error about RestSharp.

Error retrieving information from Vimeo API.
Could not load type 'RestSharp.\* < This will change based on what function I use

I am new to Oauth2 but I believe I'm doing this right.  In this specific case I'm using a personal access token I created in my Vimeo Developer page.  I've tried to upgrade to a new version of RestSharp but that just results in any Vimeo query freezing up the program.

Any ideas?

```
protected async void Page_Load(object sender, EventArgs e)
{
    try
    {
        VimeoClient VC;
        VC = CreateAuthenticatedClient();
        Task<User> account = VC.GetAccountInformationAsync();

        User accountResult = await account;
        Response.Write(accountResult.name);
    }
    catch (Exception ex)
    {
        Response.Write(ex.Message + "<br />" + ex.InnerException);
    }
}

private VimeoClient CreateUnauthenticatedClient()
{
    return new VimeoClient(ClientID, ClientSecret);
}

private VimeoClient CreateAuthenticatedClient()
{
    return new VimeoClient(AccessToken);
}
```

Thanks,
Michael

**Comment by ajbeaven** [comment]
Updating RestSharp to version 105.1.0 fixed the authentication error I was getting.

**Comment by mfilippov** [comment]
@mackeym @ajbeaven Fixed
