### ISSUE TITLE
Example video information

### ISSUE THREAD

**Issue by pattyg** [mfilippov/vimeo-dot-net#51]
Please help me. I use vimeo api for get thumb and download link of my private video allow URL. 
I tre to use this library but I don't understand the Step. Do You have an example?

**Comment by mfilippov** [comment]
Yes, you can do it. You need to create the app and issue access token for your app on the developer portal https://developer.vimeo.com/apps or you can use OAuth for getting the access token.

**Comment by mfilippov** [comment]
@pattyg You can see on integration tests in this project.

**Comment by mfilippov** [comment]
Close as answered.
