### ISSUE TITLE
RestSharp IRestResponse on client.Execute hangs forever 

### ISSUE THREAD

**Issue by SoulOfUniverse** [mfilippov/vimeo-dot-net#52]
Not sure whether this is part of your solution issue, also looking at the code you are using async task a bit in wrong approach. 
After retrieving authorization code, trying to call vimeoclient.GetAccessToken specifying the same redirect_uri as in previous step just  hangs application and doesn't get response, I assume there are issues with RestSharm version used in that build.

**Comment by joaomarcosfg** [comment]
Hello! I am having the same trouble here. Anytime that the fucntion "request.ExecuteRequestAsync" is called the application doesn't get response.

**Comment by Snipsnoop** [comment]
Same issue. hangs forever

**Comment by mfilippov** [comment]
@SoulOfUniverse @joaomarcosfg @Snipsnoop Try to latest version. I remove the RestSharp dependency.
