### ISSUE TITLE
package restore failed rolling back package changes

### ISSUE THREAD

**Issue by hammad-tariq** [mfilippov/vimeo-dot-net#53]
I am working on windows 10 universal app and trying to install "VimeoDotNet" from "nuget". and getting error "package restore failed rolling back package changes".  I have tried with multiple versions available their but same error for all.

**Comment by mfilippov** [comment]
@hammad-tariq Issue still actual?

**Comment by mfilippov** [comment]
@hammad-tariq I close this issue as obsolete.
