### ISSUE TITLE
Errror Authenticating With AccessToken.

### ISSUE THREAD

**Issue by edikep2000** [mfilippov/vimeo-dot-net#55]
Hello, Please I think this is an issue with this library. I have upgraded restsharp, downgraded, the works and it still does not work

Could not load type 'RestSharp.Authenticators.IAuthenticator' from assembly 'RestSharp, Version=105.1.0.0, Culture=neutral, PublicKeyToken=null'.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.TypeLoadException: Could not load type 'RestSharp.Authenticators.IAuthenticator' from assembly 'RestSharp, Version=105.1.0.0, Culture=neutral, PublicKeyToken=null'.

Source Error: 

```
Line 26:         public static IEnumerable<Video> GetPromoVideos()
Line 27:         {
Line 28:             var albums = new VimeoDotNet.VimeoClient(accessToken).GetAlbumVideos(383121, null, null, null, null);
Line 29:             if (albums.total > 0)
Line 30:             {
```

**Comment by mfilippov** [comment]
@edikep2000 Fixed.
