### ISSUE TITLE
Update to 0.8.2 does not retreive videos

### ISSUE THREAD

**Issue by deepikaperi** [mfilippov/vimeo-dot-net#56]
After updating vimeodotnet to 0.8.2 and restsharp to 105.2.3, when i call the method

var client = new VimeoClient(accessToken);
var vimeos = await client.GetVideosAsync();

I get error: "error":"You must provide a search query.".
We were using an old version of vimeodotnet  earlier that used 
var vimeos = await client.GetAccountVideosAsync();
to get the videos.

I have tried the solutions suggested in #43 using the Task.Run() but it still gives me the same error.

I tried the getting a single video with clip Id as below and it works fine
var video = await client.GetVideoAsync(clipid); 

Update:
i tried passing my useid and use the GetUserVideosAsync() menthod and it worked.
a Check and i realized that the endpoint called does not seem to append me

https://api.vimeo.com/videos?access_token=xxxxxxx
instead of
https://api.vimeo.com/me/videos?access_token=xxxxxxx

Am i missing something?

Thanks,
Deepika

**Comment by deepikaperi** [comment]
I have tried the solutions suggested in #43 using the Task.Run() but it still gives me the same error.

**Comment by mfilippov** [comment]
@deepikaperi Requests for "me" not implemented yet. You can pass you user id as parameter as workaround.

**Comment by mfilippov** [comment]
@deepikaperi I implemented UserId. Me support for requests. Try to use the latest  version.
