### ISSUE TITLE
Issue while getting video details

### ISSUE THREAD

**Issue by sandeep2012** [mfilippov/vimeo-dot-net#57]
https://vimeo.com/api/oembed.xml?url=https://vimeo.com/162051777/aca54578e2

I am not getting title, description like wise. Please help me.

Thanks
Sandeep

**Comment by Vineet009** [comment]
i am doing integration with my MVC app, may i know what is step by step procedure to get it done, getting error first do outh2 authentication please help

**Comment by mfilippov** [comment]
@sandeep2012 @Vineet009 Sorry for the long delay. Are your issues still actual?

**Comment by mfilippov** [comment]
Close as obsolete.
