### ISSUE TITLE
Exception "Error uploading file chunk" in UploadEntireFileAsync

### ISSUE THREAD

**Issue by PaoloLeva** [mfilippov/vimeo-dot-net#58]
We randomly get this exception when calling "UploadEntireFileAsync" in our Azure Worker. Usually it works fine (9 of 10 videos) but sometimes it fails. We cannot see any pattern on why and when it happens, and when we call this again on the same video it usually works.
Videos are typically between 30 seconds to up to 3-4 minutes.
We just updated to 0.8.2 but this does not seem to help.
Any suggestion?

**Comment by PaoloLeva** [comment]
Hints? Anyone?

**Comment by NickMoores** [comment]
We're receiving this too in 0.8.2.0.  Any suggestions?

**Comment by PaoloLeva** [comment]
I have the feeling this is due to the new rate limiting of Vimeo, but no hard prove for that. So I am still waiting for a solution me too.

**Comment by NickMoores** [comment]
I think ours was caused by this problem: https://vimeo.com/forums/api/topic:283031

**Comment by PaoloLeva** [comment]
Thanks @NickMoores 
The thread doesn't seem to offer a solution, have you found a solution? This morning nothing worked with VIMEO, right now everything works... It feels very shaky. We use a quite powerful Azure Worker and most videos are very short, so I believe that performances from our side are quite OK.

**Comment by Dashron** [comment]
This is likely not due to the rate limiting. Rate limiting does not apply to the specific upload chunks, just the calls to api.vimeo.com.

It may be related to the forum post made by @NickMoores, Vimeo is still investigating the possible cause.

**Comment by PaoloLeva** [comment]
I think this one can be closed

**Comment by abin-aot** [comment]
@NickMoores @mfilippov  - We are still getting this issue. Anyone got a fix for this ?

**Comment by Pravinnsukre** [comment]
Its is Fixed Or Not ? It is Fixed How to Fixed Please Suggest me. Thanks For any Comment Got there my Answer

**Comment by Pravinnsukre** [comment]
It is Fixed Or Not ? It is Fixed how to Fix it.

**Comment by mfilippov** [comment]
I can't reproduce this issue, I hope it will fixed when I rewrite upload to TUS.
