### ISSUE TITLE
Can the vimeo videos tracked using jquery on user back office ?

### ISSUE THREAD

**Issue by coanetworks** [mfilippov/vimeo-dot-net#73]
Hi i am using vimeoplayer on my website for playing videos, the videos are embeded using iframe. I a have requirement of tracking the videos play time in my backoffice. Is it possible to track the videos which are embeded using vimeo player?

**Comment by mfilippov** [comment]
Yes it's possible you can subscribe on event from the vimeo player: https://github.com/vimeo/player.js#timeupdate

**Comment by coanetworks** [comment]
Thank you for fast reply.I gone through the document before and i wrote some code based on the iframe id. but it does work. I will the code you can see it

**Comment by coanetworks** [comment]
[aspxfile.txt](https://github.com/mfilippov/vimeo-dot-net/files/695866/aspxfile.txt)
[Tracking code.txt](https://github.com/mfilippov/vimeo-dot-net/files/695869/Tracking.code.txt)

**Comment by mfilippov** [comment]
@coanetworks I made an example for you: https://jsfiddle.net/g1eL8d3t/3/ time update event worked.
