### ISSUE TITLE
vimeo video tracking

### ISSUE THREAD

**Issue by coanetworks** [mfilippov/vimeo-dot-net#74]
Is it possible to insert data from vimeoplayer to database that the player is "PLAYING" when it is playing mode and "PAUSED" when it is in paused mode and "COMPLETED" when it is ended.
I wrote a code like this

   player.on('play',function (event) {
                                
                                playerStart(this, videoID, '');
                                
                            });
                            player.on('pause', function (event) {playerPaused(videoID); 
                          
                            });                             
                            player.on('ended',function () { playerCompletedEvent(videoID); 
                               
                            }); 
Tracking code in seperate file

var PlayerObjs = {};
var arrays_created = 0;
var TimersForPLayer = {};
var CompletedPlayers = {};
var trackingIDs = {};
var strids = "0";
function playerStart(player, videoID, hdnvarID) {                         
        if (strids.indexOf(videoID) < 0) {
               TimersForPLayer[videoID] = 0;
               CompletedPlayers[videoID] = 0;
               trackingIDs[videoID] = 0;
               if (strids == "0")
            {
                   strids = videoID;
            }else{
                   strids = strids + "," + videoID;                
            }
        }   
    
    if (TimersForPLayer[videoID] == 0) {
        if ($(PlayerObjs[videoID]).length > 0) {
            TimersForPLayer[videoID] = 1;
            window.setInterval("trapCode(" + videoID + ",'" + hdnvarID + "')", (videoUpdateDuration*1000));
        }
        else {
            PlayerObjs[videoID] = player;
            TimersForPLayer[videoID] = 1;
            window.setInterval("trapCode(" + videoID + ",'" + hdnvarID + "')", (videoUpdateDuration*1000));
        }
    }
}
function trapCode(videoID, trackerid) {
    if (CompletedPlayers[videoID] == 0) {
        sendAjaxCall(videoID);
        if (trackerid != "") {
            if ($('#' + trackerid).length > 0) {
                $('#' + trackerid).val(trackingIDs[videoID]);
            }
        }
    }
}
function playerCompletedEvent(videoID) {
    CompletedPlayers[videoID] = 1;
    sendAjaxCall(videoID);
}
function playerPaused(videoID) {
    sendAjaxCall(videoID);
}
function sendAjaxCall(videoID) {
    try {
        $.post("Tracking.aspx",
        { 'MemberID': sessionMemberId,
            'ProspectID': sessionProspectId,
            'VideoID': videoID,
            'WebSiteID': sessionWebSiteId,
            'WatchVideoID': trackingIDs[videoID],
            'IsVideoManager': false,
            'ReturnedFromAsp': false,
            'PlayTime': parseInt(PlayerObjs[videoID].getPosition()),
            'PlayerStatus': PlayerObjs[videoID].getState(),
            'BrowserAgentName': browserName,
            "t=": Math.random()
        },
        function (data) {
            if (trackingIDs[videoID] == 0) {
                trackingIDs[videoID] = data;
            }
        }
    );
    }
    catch (ex) {
    }
}

This code should send an Ajax call to the 'Tracking.aspx' file. By using  'Tracking.aspx.cs' file i have to insert status into database.
The vimeoplayer is having event like " event = Object {seconds: 30.05, percent: 0.135, duration: 222.99}"
I want an event like "event = Object {oldstate: "PAUSED", newstate: "PLAYING"}" to insert into my database.
Is the vimeoplayer  support event objects like state?

**Comment by coanetworks** [comment]
Is it possible to track videos in this way please give answer? If it is not possible also no problem i am already using another player to track, we just want to know is it possible with vimeo player because we are the Pro member in vimeo.

**Comment by mfilippov** [comment]
Yes it's possible you can subscribe on event from the vimeo player: https://github.com/vimeo/player.js#timeupdate
You should use Vimeo video player for it.
I made an example for you: https://jsfiddle.net/g1eL8d3t/3/ time update event worked.

**Comment by coanetworks** [comment]
I am using vimeo embeded code in my website to play video.Is not the vimeo player? where i can get vimeo video player?

**Comment by mfilippov** [comment]
Close as obsolete.
