### ISSUE TITLE
Update Album not working.

### ISSUE THREAD

**Issue by JoyJoseJS** [mfilippov/vimeo-dot-net#76]
I created a vimeo App with all necessary Scopes(permissions). But requests just submitting without error. But it's not reflecting in vimeo. Could you please help me.

**Comment by mfilippov** [comment]
Could you show me your code example.

**Comment by JoyJoseJS** [comment]
Here is my Code. 
` VimeoClient VC = new VimeoClient("my Access Token");
 
// Create Album
UserKey.VimeoClient.CreateAlbumAsync(new VimeoDotNet.Parameters.EditAlbumParameters 
{ Name = txtName.Text, Description = txtDescription.Text,
Privacy = VimeoDotNet.Parameters.EditAlbumPrivacyOption.Anybody });
 
// Update Album
VC.UpdateAlbumAsync(12345
, new VimeoDotNet.Parameters.EditAlbumParameters { Name = txtName.Text, Description = txtDescription.Text });`

**Comment by mfilippov** [comment]
@JoyJoseJS I can't reproduce your issue. This test passed and has similar code: https://github.com/mfilippov/vimeo-dot-net/blob/f1738510c1ba1f0c11d48b8c79eace6d83c7365f/src/VimeoDotNet.Tests/VimeoClientAsyncTests.cs#L375
May be the issue already fixed. Could you check it?

**Comment by mfilippov** [comment]
@JoyJoseJS I close this issue as obsolete. If your problem not resolved, please write about it.
