### ISSUE TITLE
+10GB file upload never verifies as completed

### ISSUE THREAD

**Issue by martindandanell** [mfilippov/vimeo-dot-net#79]
Great library, guys.

I've tested the upload operation extensively with two file sizes:

- ~1GB
- ~15GB

The first one always succeeds as expected, but the latter one is never able to verify that the operation has indeed finished (making my implementation wait indefinitely).

Tracing the source code flow, I suspect that the issue might originate from the use of **32bit** integers when extracting **Range** indexes in the `VerifyUploadFileAsync()` method:

```csharp
int startIndex = 0;
int endIndex = 0;
Parameter rangeHeader =
response.Headers.FirstOrDefault(h => string.Compare(h.Name, "Range", true) == 0);
if (rangeHeader != null && rangeHeader.Value != null)
{
    Match match = RangeRegex.Match(rangeHeader.Value as string);
    if (match.Success
        && int.TryParse(match.Groups["start"].Value, out startIndex)
        && int.TryParse(match.Groups["end"].Value, out endIndex))
    {
        verify.BytesWritten = endIndex - startIndex;
        if (verify.BytesWritten == uploadRequest.FileLength)
        {
            verify.Status = UploadStatusEnum.Completed;
        }
    }
}
```

`verify.BytesWritten` variable is always 0, so I expect that the `int.TryParse()` method fails silently.

**Comment by mfilippov** [comment]
@martindandanell Fixed
