### ISSUE TITLE
Synchronous methods can result in deadlock.

### ISSUE THREAD

**Issue by MisinformedDNA** [mfilippov/vimeo-dot-net#8]
I tried using the synchronous methods (I was being lazy) in a WebApi and kept getting a deadlock. You can read about why that happens [here](http://blogs.msdn.com/b/pfxteam/archive/2012/04/13/10293638.aspx).

If you *really* want to keep sync them, you would need to offload the work to another thread like so

```
int Sync() 
{ 
    return Task.Run(() => Library.FooAsync()).Result; 
}
```

But as the above link says, this should be avoided unless it is absolutely necessary.

> should you expose synchronous wrappers for asynchronous methods? Please try hard not to; leave it up to the consumer of [your] method to do so if they must

Based on this I recommend that all synchronous methods be removed.

**Comment by FoC-** [comment]
Please try to use it like, it should help: 

``` csharp
int Sync() 
{ 
    return Task.Run(async () => await Library.FooAsync()).Result; 
}
```

**Comment by scommisso** [comment]
```csharp
Task.Run(async () => await AsyncMethod)
   .ConfigureAwait(false)
   .GetAwaiter()
   .GetResult();
```

**Comment by scommisso** [comment]
Try #43.

**Comment by MisinformedDNA** [comment]
But like I said above: `this should be avoided unless absolutely necessary`.

Furthermore, you essentially just created a potential new and separate NuGet package `RunSynchronouslyWithCurrentCulture` as it operates completely independent of any Vimeo code.

Why not just get rid of the sync methods and offer users the `RunSynchronouslyWithCurrentCulture` code/package if they really want synchronous? You reduce you API surface making it easier to develop and maintain.
Also, in Microsoft's latest APIs, they have stopped shipping both sync and async. If there is an async version, there is no sync version.
