### ISSUE TITLE
Upload thumbnails

### ISSUE THREAD

**Issue by BrahmanandaK** [mfilippov/vimeo-dot-net#80]
Here is the code change required for uploading thumbnail to a video. make sure your image is same size as your original video size.

Picture.cs
`/// <summary>
/// link
/// </summary>
public string link { get; set; }

/// <summary>
/// resource_key
/// </summary>
public string resource_key { get; set; }`

------------------------------------------------------------------------------------------

VimeoClient_Sync.cs
`/// <summary>
        /// Set thumbnail
        /// </summary>                
        /// <param name="clipId">clipId</param>
        /// <param name="path">image path</param>
        /// <returns></returns>
        public void UploadThumbnail(long clipId, string path)
        {
            try
            {
                Picture pic = GetPictureAsync(clipId).RunSynchronouslyWithCurrentCulture();
                
                using (var file = new BinaryContent(path))
                {
                    UploadPictureAsync(file, pic.link).RunSynchronouslyWithCurrentCulture();
                }
                SetThumbnailAsync(pic.uri).RunSynchronouslyWithCurrentCulture();
            }
            catch (AggregateException ex)
            {
                ExceptionDispatchInfo.Capture(ex.InnerException).Throw();
                return;
            }
        }`
------------------------------------------------------------------------------------------------------
VimeoClient_Videos.cs
`        /// <summary>
        /// Get picture
        /// </summary>
        /// <param name="clipId">ClipId</param>
        /// <returns>Picture</returns>
        public async Task<Picture> GetPictureAsync(long clipId)
        {
            try
            {
                ThrowIfUnauthorized();

                IApiRequest request = ApiRequestFactory.GetApiRequest(AccessToken);
                request.Method = Method.POST;
                request.Path = Endpoints.Pictures;
                request.UrlSegments.Add("clipId", clipId.ToString());

                IRestResponse<Picture> response = await request.ExecuteRequestAsync<Picture>();
                UpdateRateLimit(response);
                CheckStatusCodeError(response, "Error retrieving account video.", HttpStatusCode.NotFound);

                if (response.StatusCode == HttpStatusCode.NotFound)
                {
                    return null;
                }
                return response.Data;
            }
            catch (Exception ex)
            {
                if (ex is VimeoApiException)
                {
                    throw;
                }
                throw new VimeoApiException("Error retrieving account video.", ex);
            }
        }

        /// <summary>
        /// upload picture asynchronously
        /// </summary>        
        /// <param name="fileContent">fileContent</param>
        /// <param name="link">link</param>
        /// <returns>upload pic </returns>
        public async Task UploadPictureAsync(IBinaryContent fileContent, string link)
        {
            try
            {
                if (!fileContent.Data.CanRead)
                {
                    throw new ArgumentException("fileContent should be readable");
                }
                if (fileContent.Data.CanSeek && fileContent.Data.Position > 0)
                {
                    fileContent.Data.Position = 0;
                }
                ThrowIfUnauthorized();
                IApiRequest request = ApiRequestFactory.GetApiRequest(AccessToken);
                request.Method = Method.PUT;
                request.Path = link;
                request.Headers.Add(Request.HeaderContentType, "image/jpeg");

                request.Headers.Add(Request.HeaderContentLength, fileContent.Data.Length.ToString());
                request.BinaryContent = fileContent.ReadAll();

                IRestResponse response = await request.ExecuteRequestAsync();

                CheckStatusCodeError(null, response, "Error generating upload ticket to replace video.");

                //return response.Data;
            }
            catch (Exception ex)
            {
                if (ex is VimeoApiException)
                {
                    throw;
                }
                throw new VimeoUploadException("Error Uploading picture.", null, ex);
            }
        }

        /// <summary>
        /// set thumbnail picture asynchronously
        /// </summary>                
        /// <param name="link">link</param>
        /// <returns>Set thumbnail pic </returns>
        public async Task SetThumbnailAsync(string link)
        {
            try
            {
                ThrowIfUnauthorized();
                IApiRequest request = ApiRequestFactory.GetApiRequest(AccessToken);
                request.Method = Method.PATCH;
                request.Path = link;
                request.Query.Add("active", "true");

                IRestResponse response = await request.ExecuteRequestAsync();

                CheckStatusCodeError(null, response, "Error Setting thumbnail image active.");

                //return response.Data;
            }
            catch (Exception ex)
            {
                if (ex is VimeoApiException)
                {
                    throw;
                }
                throw new VimeoUploadException("Error Setting thumbnail image active.", null, ex);
            }
        }`

**Comment by Adkaros** [comment]
Is it possible to get a new build with this included? I'm trying to edit the code myself but I don't see a Pictures.cs? I only see Picture.cs.

I'm also getting some errors in VimeoClient_Videos.cs in GetPictureAsync(), it doesn't have a Pictures Endpoint.

Need this for a project I am currently working on, Any choice you could publish this code or just send a dll with it included? Thanks!

**Comment by BrahmanandaK** [comment]
It was type. Modify Picture.cs.

**Comment by Adkaros** [comment]
For anyone trying to get this working,

I had to change function signature
public async Task GetPictureAsync(long clipId)
to
public async Task<Picture> GetPictureAsync(long clipId)

I also needed to add this to Endpoints.cs
public const string Pictures = "/videos/{clipId}/pictures";

Then just built as class library and imported dll to project, thanks for the code BrahmanadaK!

**Comment by mohibsheth** [comment]
I have integrated changes from comments and updated it as per new code structure.

**Comment by mfilippov** [comment]
Fixed.
