### ISSUE TITLE
Whitelist documentation reference but can't find the docs

### ISSUE THREAD

**Issue by surrealcoder** [mfilippov/vimeo-dot-net#82]
I'm referring to this comment
https://github.com/mfilippov/vimeo-dot-net/blob/master/src/VimeoDotNet/Models/VideoUpdateMetadata.cs#L31

is there any chance there are docs for using this feature? I'm having trouble figuring out the correct call.

**Comment by mfilippov** [comment]
I cannot add tests because this feature worked only on PRO accounts.
