### ISSUE TITLE
Error when retrieving account information

### ISSUE THREAD

**Issue by mahboobcse** [mfilippov/vimeo-dot-net#83]
VimeoDotNet.VimeoClient vc = new VimeoDotNet.VimeoClient(ACCESS_TOKEN);
User account = vc.GetAccountInformation();

I get an error:

An unhandled exception of type 'VimeoDotNet.Exceptions.VimeoApiException' occurred in mscorlib.dll
Additional information: Error retrieving account information.

From code debugging get Status = WaitingForActivation

**Comment by mohibsheth** [comment]
I checked this and worked fine for without any error.

@mahboobcse Could you try again? If error still persists, could you provide with a reproducible repo?

**Comment by mfilippov** [comment]
@mahboobcse Is issue actual?

**Comment by mfilippov** [comment]
@mahboobcse I closed issue as obsolete. If you still have the problem please reopen it.

**Comment by kristoffer-tvera** [comment]
I'm experiencing almost the same issue. When getting account info or ANYTHING, the async tasks will just not work, and their status is stuck on 'WaitingForActivation'. 
Project is a Webapplication targeting .Net Framework 4.7

**Comment by mfilippov** [comment]
@kristoffer-tvera Thanks for the information I try to check it.

**Comment by mfilippov** [comment]
@kristoffer-tvera I think I fix issue in latest version.
