### ISSUE TITLE
Error generating upload ticket.

### ISSUE THREAD

**Issue by harshidamodi** [mfilippov/vimeo-dot-net#85]
Hello

I want to upload my video stream to vimeo
I got this error into InnerException
"Could not load type 'RestSharp.Authenticators.IAuthenticator' from assembly 'RestSharp, Version=105.1.0.0, Culture=neutral, PublicKeyToken=null'."

My Code:
Note: Error throw from "vc.StartUploadFile(bc, contentLength)"

 public static string UploadVideo(MemoryStream filestream,  int contentLength)
        {
            try
            {
                VimeoDotNet.VimeoClient vc = new VimeoDotNet.VimeoClient("Bearer **********...");              
                var binaryReader = new BinaryReader(filestream);
                BinaryContent bc = new BinaryContent(filestream, "video/mp4");
                vc.StartUploadFile(bc, contentLength);  

            }

            catch (Exception h)
            {

                throw;
            }

           
            return "Failed";
        }

**Comment by mfilippov** [comment]
@harshidamodi I remove the RestSharp dependency from the latest version. The issue should by fixed.
