### ISSUE TITLE
Unauthenticated tokens flow

### ISSUE THREAD

**Issue by yaliashkevich** [mfilippov/vimeo-dot-net#87]
Is it possible to get access token based on client_id/client_secret?

Generate unauthenticated tokens:
https://developer.vimeo.com/api/authentication

Haven't find any suitable method.

**Comment by mfilippov** [comment]
@yaliashkevich Thanks for the feedback I add support unauthenticated tokens. Look on test: for more info: https://github.com/mfilippov/vimeo-dot-net/blob/9f60a4168b7223f7d2556475e25e67a32e273cf7/src/VimeoDotNet.Tests/VimeoClientAsyncTests.cs#L595
