### ISSUE TITLE
Nuspec has wrong RestSharp version

### ISSUE THREAD

**Issue by yaliashkevich** [mfilippov/vimeo-dot-net#88]
Just installed to the package from nuget using:

`Install-Package VimeoDotNet -Version 0.8.3.48`

which installs RestSharp 105.1.0 as a dependency:
`<dependency id="RestSharp" version="105.1.0" />`

Attempt to use any VimeoClient method results in TypeLoadException:

`System.TypeLoadException: Could not load type 'RestSharp.Authenticators.IAuthenticator' from assembly 'RestSharp, Version=105.1.0.0, Culture=neutral, PublicKeyToken=null'.`

There is mismatch of RestSharp versions used by the lib and defined in nuspec package.

**Comment by mfilippov** [comment]
Thanks for the feedback I try to fix it at the weekend.
