### ISSUE TITLE
GetAlbumsAsync error

### ISSUE THREAD

**Issue by kamnaz** [mfilippov/vimeo-dot-net#95]
With the latest update this line gives an error:

var albums = await client.GetAlbumsAsync(new VimeoDotNet.Parameters.GetAlbumsParameters { PerPage = 50 });

And the error is "System.Net.ProtocolViolationException: Cannot send a content-body with this verb-type."

Any workarounds?

Thanks,
Kam

**Comment by mfilippov** [comment]
@kamnaz I fix issues in "GET" request processing and add the test for your case. Thank you for the report.
