### ISSUE TITLE
Unable to Upload

### ISSUE THREAD

**Issue by dcalens** [mfilippov/vimeo-dot-net#96]
Starting with the 0.9.X releases, I am unable to upload using binarycontent loaded from a file.  The offending code is line 372 in VimeoClient_Upload.cs

`request.Body = new ByteArrayContent(await fileContent.ReadAsync(startIndex, endIndex), (int)startIndex, (int)endIndex);`

After the initial chunk is sent, the second time through the third parameter is out of range.

**Comment by MattHartz** [comment]
@mfilippov I created a pull request for this #99

**Comment by mfilippov** [comment]
Fixed in 0.9.0.11
